# -*- coding: utf-8 -*-
"""trail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhpHHBfV5R0NO3IG2KDi4lvNZBCLT3-A
"""

pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random
import matplotlib.pyplot as plt
import seaborn as sns

fake = Faker()

data = []

departments = ['CSE', 'IT', 'ECE']
years = ['1st', '2nd', '3rd']
genders = ['Male', 'Female']

for i in range(250):
    maths = random.randint(35, 100)
    science = random.randint(35, 100)
    english = random.randint(35, 100)

    attendance = random.randint(50, 100)
    internal = random.randint(0, 25)

    data.append([
        i+1,
        fake.name(),
        random.choice(genders),
        random.choice(departments),
        random.choice(years),
        maths,
        science,
        english,
        attendance,
        internal
    ])

columns = ["Student_ID", "Name", "Gender", "Department", "Year",
           "Maths", "Science", "English", "Attendance", "Internal"]

df = pd.DataFrame(data, columns=columns)

df.head()

.03dept_avg.plot(kind='bar')
plt.show()

plt.scatter(df['Attendance'], df['Average'])
plt.show()

df['Average'].hist()
plt.show()

sns.countplot(x='Department', data=df)
plt.show()

df.head()